import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "WeSee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className=" text-white p-4" style={{backgroundColor:"#6441A4"}}>
      <div className="container mx-auto flex justify-between items-center">
        <Link href="/" className="text-xl font-bold">WeSee</Link>
        <div className="hidden md:flex space-x-6">
          <Link href="/" className="hover:text-gray-300">Crée Compte</Link>
          <Link href="/" className="hover:text-gray-300">Se connecter</Link>
          
        </div>
        <button className="md:hidden flex items-center px-3 py-2 border rounded text-white border-white hover:bg-white hover:text-blue-600">
          hidden
        </button>
      </div>
    </nav>
        {children}
      </body>
    </html>
  );
}
